### ISSUE TITLE
Error NMPC Problem Formulation

### ISSUE THREAD

**Issue by Betancourt20** [deng-haoyang/ParNMPC#8]
Hello,
First, thank you for share with us your work.
I was trying to run the first example but I got the following error
>>>>
NMPC_Problem_Formulation
Error using sym/vertcat (line 17)
Error using maplemex
Error, (in ArrayTools:-Concatenate) number of columns must match

Error in DynamicSystem/setf (line 5)
        obj.f = symfun(f,[obj.u;obj.x;obj.p]);

Error in OptimalControlProblem/setf (line 2)
    setf@DynamicSystem(OCP,f);

Error in NMPC_Problem_Formulation (line 33)
OCP.setf(f);
 >>>>>>>>
I hope you can help with this.
Best regards,
Julio

**Comment by deng-haoyang** [comment]
Hi Julio,

Thanks for the feedback.

It seems you have installed Maple and the Maple sym function is called instead of the MATLAB one. 
Can you try "u = sym('u',[4,1])" in MATLAB and see if u is a 4x1 vector? 

Look forward to your response.
Deng

**Comment by Betancourt20** [comment]
Hi,
Thank you for your response. Here is the Matlab console give after the command you told me before :
>> u = sym('u',[4,1])
 
u =
 
                               [u1, u2, u3, u4]
Thank you in advance,
Julio Beancourt

**Comment by deng-haoyang** [comment]
Hi Julio,

Thanks for the response.

It seems that the sym function didn't return the right result (4x1 vector) because of the bug caused by the Maple sym function.

I have updated the source code to guard this and the problem might have been solved .
Alternatively, you can call the Matlab sym function rather than the maple one by removing the maple path from MATLAB search path.

I hope this could solve the problem.
Thank you.
Deng

**Comment by Betancourt20** [comment]
Hi Deng,
In fact as you said before, the problem was the symbolic Maple toolbox. So, I uninstalled the toolbox and that's it. Right now is working. 
Thank you so much for your help

Best regards,
Julio
